### ISSUE TITLE
BUG: OSX: Option+Key no longer works, produces garbage

### ISSUE THREAD

**Issue by JosephPecoraro** [QW-Group/ezquake-source#111] opened 2016-07-09 08:21 UTC
On OS X, Option+Key no longer works.
1. Show console
2. Type "this" without option produces white text "this"
3. Type "this" holding option produces garbage

Expected Typing "this" holding option to produce alternate color (gold/red) text.

This broke with:
6ac7059 Initial changes to support non-american keyboard layouts & cyrillic characters.

**Comment by JosephPecoraro** [comment] 2016-07-09 08:45
After some discussion on discord:

    /in_builtinkeymap 1

Fixes the issue.

**Comment by meag** [comment] 2016-07-29 15:22
Regarding the discussion on Discord: on Windows, alternate color (gold/red) is acccessed when alt is held down, the problem is that ezQuake uses option as the alt-equivalent, meanwhile osx interprets option as a deadkey modifier similar to alt-gr, so produces an alternative character (option+e = é ?  that kind of thing) which ezQuake then uses when `/in_builtinkeymap 0`.

Still an open issue, because `/in_builtinkeymap 1` is presumably not a valid solution for non-qwerty keyboard layouts.

**Comment by meag** [comment] 2020-12-15 21:08
Just a note for future (no osx here to test on) but could we capture SDLK_LGUI / SDLK_RGUI being pressed, and suppress in keyb_textinputevent() if they're currently down?  So it would be a bit like `/in_builtinkeymap 1` but only when the option key is held down?  or maybe that messes with too many configs...

**Comment by tcsabina** [comment] 2022-10-17 22:25
Not sure in which version of exquake the fix was added, but it is for sure in a recent version (3.6.x).
Closing

**Closed by tcsabina** 2022-10-17 22:25 UTC
Labels: macos-only
