### ISSUE TITLE
BUG: r_fx_geometry incorrect behavior in smaller viewsize's

### ISSUE THREAD

**Issue by mushis** [QW-Group/ezquake-source#792] opened 2023-07-02 21:52 UTC
**ezQuake version:**
3.6.2 f7ba65d

**OS/device including version:**
windows 10

**Describe the bug**
`r_fx_geometry` is miscalculated when screen size smaller than 100

**To Reproduce**
```
/r_fx_geometry 1
/viewsize 90
```

**Expected behavior**
nice lines :)

**Screenshots**
![ezquake000](https://github.com/QW-Group/ezquake-source/assets/3011167/603f1960-3679-431e-a144-c3bfcc01fdc4)
This screenshot is with `viewsize 90`

**Additional context**

**Comment by zigg1zagg1** [comment] 2023-07-03 05:56
Duplicate of https://github.com/QW-Group/ezquake-source/issues/598 no?
It also happens with cl_sbar 1

**Comment by tcsabina** [comment] 2023-09-13 19:02
Fixed with #800

**Closed by tcsabina** 2023-09-13 19:02 UTC
